;;Map elms are for C, M, C-S, M-S, C-M-S

(setq iterm-regular-character-map
      '((?a (?a ?a ?A ?A ?A))
        (?b (?b ?b ?B ?B ?B))
        (?c (?c ?c ?C ?C ?C))
        (?d (?d ?d ?D ?D ?D))
        (?e (?e ?e ?E ?E ?E))
        (?f (?f ?f ?F ?F ?F))
        (?g (?g ?g ?G ?G ?G))
        (?h (?h ?h ?H ?H ?H))
        (?i (?i ?i ?I ?I ?I))
        (?j (?j ?j ?J ?J ?J))
        (?k (?k ?k ?K ?K ?K))
        (?l (?l ?l ?L ?L ?L))
        (?m (?m ?m ?M ?M ?M))
        (?n (?n ?n ?N ?N ?N))
        (?o (?o ?o ?O ?O ?O))
        (?p (?p ?p ?P ?P ?P))
        (?q (?q ?q ?Q ?Q ?Q))
        (?r (?r ?r ?R ?R ?R))
        (?s (?s ?s ?S ?S ?S))
        (?t (?t ?t ?T ?T ?T))
        (?u (?u ?u ?U ?U ?U))
        (?v (?v ?v ?V ?V ?V))
        (?w (?w ?w ?W ?W ?W))
        (?x (?x ?x ?X ?X ?X))
        (?y (?y ?y ?Y ?Y ?Y))
        (?z (?z ?z ?Z ?Z ?Z))
        ))

(setq iterm-number-character-map
        '((?1 (?1 ?1 ?\! ?\! ?\!))
        (?2 (?2 ?2 ?\@ ?\@ ?\@))
        (?3 (?3 ?3 ?\# ?\# ?\#))
        (?4 (?4 ?4 ?\$ ?\$ ?\$))
        (?5 (?5 ?5 ?\% ?\% ?\%))
        (?6 (?6 ?6 ?^ ?^ ?^))
        (?7 (?7 ?7 ?& ?& ?&))
        (?8 (?8 ?8 ?\* ?\* ?\*))
        (?9 (?9 ?9 ?\( ?\( ?\())
        ))

(setq iterm-symbol-character-map
        '((?\` (?\` ?\` ?\~ ?\~ ?\~))
         (?\- (?\- ?\- ?\_ ?\_ ?\_))
         (?\= (?\= ?\= ?\+ ?\+ ?\+))
         (?\[ (?\[ ?\[ ?\{ ?\{ ?\{))
         (?\] (?\] ?\] ?\} ?\} ?\}))
         (?\\ (?\\ ?\\ ?\| ?\| ?\|))
         (?\; (?\; ?\; ?\: ?\: ?\:))
         (?\' (?\' ?\' ?\" ?\" ?\"))
         (?\, (?\, ?\, ?\< ?\< ?\<))
         (?\. (?\. ?\. ?\> ?\> ?\>))
         (?\/ (?\/ ?\/ ?\? ?\? ?\?))
        ))

(defun chopps-add-local-keys (&optional frame)
  (let ((keymap function-key-map))    ; was local-function-key-map

    ;; ;; These are apparently the xterm defaults (there are others for mod combos)
    (define-key keymap "\e[1;2A" [S-up])
    (define-key keymap "\e[1;2B" [S-down])
    (define-key keymap "\e[1;2C" [S-right])
    (define-key keymap "\e[1;2D" [S-left])

    (define-key keymap "\e[1;3A" [M-up])
    (define-key keymap "\e[1;3B" [M-down])
    (define-key keymap "\e[1;3C" [M-right])
    (define-key keymap "\e[1;3D" [M-left])

    (define-key keymap "\e[1;9A" [M-up])
    (define-key keymap "\e[1;9B" [M-down])
    (define-key keymap "\e[1;9C" [M-right])
    (define-key keymap "\e[1;9D" [M-left])

    (define-key keymap "\e[1;5A" [C-up])
    (define-key keymap "\e[1;5B" [C-down])
    (define-key keymap "\e[1;5C" [C-right])
    (define-key keymap "\e[1;5D" [C-left])

    (define-key keymap "\e[1;6A" [C-S-up])
    (define-key keymap "\e[1;6B" [C-S-down])
    (define-key keymap "\e[1;6C" [C-S-right])
    (define-key keymap "\e[1;6D" [C-S-left])

    (define-key keymap "\e[1;4A" [M-S-up])
    (define-key keymap "\e[1;4B" [M-S-down])
    (define-key keymap "\e[1;4C" [M-S-right])
    (define-key keymap "\e[1;4D" [M-S-left])

    (define-key keymap "\e[1;10A" [M-S-up])
    (define-key keymap "\e[1;10B" [M-S-down])
    (define-key keymap "\e[1;10C" [M-S-right])
    (define-key keymap "\e[1;10D" [M-S-left])

    (define-key keymap (kbd "ESC \" 2 R") '[S-return])
    (define-key keymap (kbd "ESC \" 2 T") '[backtab])

    (define-key keymap (kbd "ESC \" 5 r") '[C-return])
    (define-key keymap (kbd "ESC \" 5 2") '[C-2])
    (define-key keymap (kbd "ESC \" 5 ;") '[?\C-\;])
    (define-key keymap (kbd "ESC \" 5 :") '[?\C-\:])
    (define-key keymap (kbd "ESC \" 5 ,") '[?\C-\,])
    (define-key keymap (kbd "ESC \" 5 .") '[?\C-\.])
    (define-key keymap (kbd "ESC \" 5 >") '[?\C-\>])
    (define-key keymap (kbd "ESC \" 5 <") '[?\C-\<])
    (define-key keymap (kbd "ESC \" 5 /") '[?\C-\/])
    (define-key keymap (kbd "ESC \" 5 ?") '[?\C-\?])
    (define-key keymap (kbd "ESC \" 5 \'") '[?\C-\'])
    (define-key keymap (kbd "ESC \" 5 \"") '[?\C-\"])
    (define-key keymap (kbd "ESC \" 5 |") '[?\C-|])
    (define-key keymap (kbd "ESC \" 5 \\") '[?\C-\\])

    (define-key keymap (kbd "ESC \" 5 t") '[C-tab])

    (define-key keymap (kbd "ESC \" 5 T") '[C-backtab])
    (define-key keymap (kbd "ESC \" 7 R") '[C-S-return])

    (define-key keymap (kbd "ESC \" 7 2") '[C-S-2])
))

(chopps-add-local-keys)

(provide 'iterm-custom-keys)
